package com.czjk.bleDemo.model;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

import java.util.Comparator;

/**
 * Entity mapped to table "SCALE_RECORD".
 */
public class ScaleRecord implements java.io.Serializable {

    public Long id;
    public Integer IsSend;
    public String UserId;
    public String DeviceId;
    public Long Timestamp;
    public String BatchId;
    public Integer ScaleType;
    public String sensorValue_01;
    public String sensorValue_02;
    public String sensorValue_03;
    public String sensorValue_04;
    public String sensorValue_05;
    public String sensorValue_06;
    public String sensorValue_07;
    public String sensorValue_08;
    public String sensorValue_09;
    public String sensorValue_10;
    public String sensorValue_11;
    public String sensorValue_12;
    public String sensorValue_13;
    public String sensorValue_14;
    public String sensorValue_15;
    public String sensorValue_16;
    public String sensorValue_17;
    public String sensorValue_18;
    public String sensorValue_19;
    public String sensorValue_20;

    // KEEP FIELDS - put your custom fields here
    //IsSend:0:未上传 1：上传中 2：上传完成 3:修改 4:正在下载 -1:删除
    public static final int WeightType=1; //类型为Weight 传感器存储类型为:02 06 03 04 11 12 13 21
    public static final int SportType=2;  //类型为Sport 传感器存储类型为:07 09 22 15 23 19 20 17 071 091 221 151 231 191 201 171

    public static final int StepsScaleType=21;
    public static final int SleepScaleType=22;
    public static final int HeartScaleType=23;
    public static final int WeightWifiType=24; //类型为Weight 传感器存储类型为:02 06 03 04 11 12 13 21

    public static final int[] ScaleTypes=new int[]{WeightType,SportType,StepsScaleType,SleepScaleType,HeartScaleType,WeightWifiType};

    public enum IsSendType{
        UnUP(0),UpIng(1),Finish(2),Edit(3),WifiUnClaimNew(101),WifiUnClaimOld(102);

        private final int value;
        public int Value() {
            return value;
        }
        IsSendType(int value) {
            this.value = value;
        }
    }
//    public static final int Edit=3;
//    public static final int UpIng=1;
//    public static final int Finish=2;
//    public static final int UnUP=0;

//    public static final int BmiType=3;
//    public static final int SportType=4;
//    public static final int SleepType=5;
//    public static final int HeartType=6;
//    public static final int HydrationType=7;
//    public static final int MuscleType=8;
//    public static final int BoneType=9;
//    public static final int BmrType=10;

    /*
   0   其他
   01	身高
   02	体重
   03	脂肪率
   04	水分率
   05	身体年龄
   06	BMI
   07	步数
   08	楼层数
   09	运动里程
   10	通道号
   11	肌肉率
   12	骨骼率
   13	基础代谢率
   14	活动
   15	运动时间
   16	饮水量
   17	静息心率
   18	身体阻抗
   19  深度睡眠时间
   20  浅度睡眠时间
   21  活动代谢率
   22  运动代谢
   23  睡眠时间
   */

    public void SetScaleRecord(ScaleRecord scaleRecord){
        this.IsSend = scaleRecord.getIsSend();
        this.UserId = scaleRecord.getUserId();
        this.DeviceId = scaleRecord.getDeviceId();
        this.Timestamp = scaleRecord.getTimestamp();
        this.BatchId = scaleRecord.getBatchId();
        this.ScaleType = scaleRecord.getScaleType();
        this.sensorValue_01 = scaleRecord.getSensorValue_01();
        this.sensorValue_02 = scaleRecord.getSensorValue_02();
        this.sensorValue_03 = scaleRecord.getSensorValue_03();
        this.sensorValue_04 = scaleRecord.getSensorValue_04();
        this.sensorValue_05 = scaleRecord.getSensorValue_05();
        this.sensorValue_06 = scaleRecord.getSensorValue_06();
        this.sensorValue_07 = scaleRecord.getSensorValue_07();
        this.sensorValue_08 = scaleRecord.getSensorValue_08();
        this.sensorValue_09 = scaleRecord.getSensorValue_09();
        this.sensorValue_10 = scaleRecord.getSensorValue_10();
        this.sensorValue_11 = scaleRecord.getSensorValue_11();
        this.sensorValue_12 = scaleRecord.getSensorValue_12();
        this.sensorValue_13 = scaleRecord.getSensorValue_13();
        this.sensorValue_14 = scaleRecord.getSensorValue_14();
        this.sensorValue_15 = scaleRecord.getSensorValue_15();
        this.sensorValue_16 = scaleRecord.getSensorValue_16();
        this.sensorValue_17 = scaleRecord.getSensorValue_17();
        this.sensorValue_18 = scaleRecord.getSensorValue_18();
        this.sensorValue_19 = scaleRecord.getSensorValue_19();
        this.sensorValue_20 = scaleRecord.getSensorValue_20();
    }
    // KEEP FIELDS END

    public ScaleRecord() {
    }

    public ScaleRecord(Long id) {
        this.id = id;
    }

    public ScaleRecord(Long id, Integer IsSend, String UserId, String DeviceId, Long Timestamp, String BatchId, Integer ScaleType, String sensorValue_01, String sensorValue_02, String sensorValue_03, String sensorValue_04, String sensorValue_05, String sensorValue_06, String sensorValue_07, String sensorValue_08, String sensorValue_09, String sensorValue_10, String sensorValue_11, String sensorValue_12, String sensorValue_13, String sensorValue_14, String sensorValue_15, String sensorValue_16, String sensorValue_17, String sensorValue_18, String sensorValue_19, String sensorValue_20) {
        this.id = id;
        this.IsSend = IsSend;
        this.UserId = UserId;
        this.DeviceId = DeviceId;
        this.Timestamp = Timestamp;
        this.BatchId = BatchId;
        this.ScaleType = ScaleType;
        this.sensorValue_01 = sensorValue_01;
        this.sensorValue_02 = sensorValue_02;
        this.sensorValue_03 = sensorValue_03;
        this.sensorValue_04 = sensorValue_04;
        this.sensorValue_05 = sensorValue_05;
        this.sensorValue_06 = sensorValue_06;
        this.sensorValue_07 = sensorValue_07;
        this.sensorValue_08 = sensorValue_08;
        this.sensorValue_09 = sensorValue_09;
        this.sensorValue_10 = sensorValue_10;
        this.sensorValue_11 = sensorValue_11;
        this.sensorValue_12 = sensorValue_12;
        this.sensorValue_13 = sensorValue_13;
        this.sensorValue_14 = sensorValue_14;
        this.sensorValue_15 = sensorValue_15;
        this.sensorValue_16 = sensorValue_16;
        this.sensorValue_17 = sensorValue_17;
        this.sensorValue_18 = sensorValue_18;
        this.sensorValue_19 = sensorValue_19;
        this.sensorValue_20 = sensorValue_20;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getIsSend() {
        return IsSend;
    }

    public void setIsSend(Integer IsSend) {
        this.IsSend = IsSend;
    }

    public String getUserId() {
        return UserId;
    }

    public void setUserId(String UserId) {
        this.UserId = UserId;
    }

    public String getDeviceId() {
        return DeviceId;
    }

    public void setDeviceId(String DeviceId) {
        this.DeviceId = DeviceId;
    }

    public Long getTimestamp() {
        return Timestamp;
    }

    public void setTimestamp(Long Timestamp) {
        this.Timestamp = Timestamp;
    }

    public String getBatchId() {
        return BatchId;
    }

    public void setBatchId(String BatchId) {
        this.BatchId = BatchId;
    }

    public Integer getScaleType() {
        return ScaleType;
    }

    public void setScaleType(Integer ScaleType) {
        this.ScaleType = ScaleType;
    }

    public String getSensorValue_01() {
        return sensorValue_01;
    }

    public void setSensorValue_01(String sensorValue_01) {
        this.sensorValue_01 = sensorValue_01;
    }

    public String getSensorValue_02() {
        return sensorValue_02;
    }

    public void setSensorValue_02(String sensorValue_02) {
        this.sensorValue_02 = sensorValue_02;
    }

    public String getSensorValue_03() {
        return sensorValue_03;
    }

    public void setSensorValue_03(String sensorValue_03) {
        this.sensorValue_03 = sensorValue_03;
    }

    public String getSensorValue_04() {
        return sensorValue_04;
    }

    public void setSensorValue_04(String sensorValue_04) {
        this.sensorValue_04 = sensorValue_04;
    }

    public String getSensorValue_05() {
        return sensorValue_05;
    }

    public void setSensorValue_05(String sensorValue_05) {
        this.sensorValue_05 = sensorValue_05;
    }

    public String getSensorValue_06() {
        return sensorValue_06;
    }

    public void setSensorValue_06(String sensorValue_06) {
        this.sensorValue_06 = sensorValue_06;
    }

    public String getSensorValue_07() {
        return sensorValue_07;
    }

    public void setSensorValue_07(String sensorValue_07) {
        this.sensorValue_07 = sensorValue_07;
    }

    public String getSensorValue_08() {
        return sensorValue_08;
    }

    public void setSensorValue_08(String sensorValue_08) {
        this.sensorValue_08 = sensorValue_08;
    }

    public String getSensorValue_09() {
        return sensorValue_09;
    }

    public void setSensorValue_09(String sensorValue_09) {
        this.sensorValue_09 = sensorValue_09;
    }

    public String getSensorValue_10() {
        return sensorValue_10;
    }

    public void setSensorValue_10(String sensorValue_10) {
        this.sensorValue_10 = sensorValue_10;
    }

    public String getSensorValue_11() {
        return sensorValue_11;
    }

    public void setSensorValue_11(String sensorValue_11) {
        this.sensorValue_11 = sensorValue_11;
    }

    public String getSensorValue_12() {
        return sensorValue_12;
    }

    public void setSensorValue_12(String sensorValue_12) {
        this.sensorValue_12 = sensorValue_12;
    }

    public String getSensorValue_13() {
        return sensorValue_13;
    }

    public void setSensorValue_13(String sensorValue_13) {
        this.sensorValue_13 = sensorValue_13;
    }

    public String getSensorValue_14() {
        return sensorValue_14;
    }

    public void setSensorValue_14(String sensorValue_14) {
        this.sensorValue_14 = sensorValue_14;
    }

    public String getSensorValue_15() {
        return sensorValue_15;
    }

    public void setSensorValue_15(String sensorValue_15) {
        this.sensorValue_15 = sensorValue_15;
    }

    public String getSensorValue_16() {
        return sensorValue_16;
    }

    public void setSensorValue_16(String sensorValue_16) {
        this.sensorValue_16 = sensorValue_16;
    }

    public String getSensorValue_17() {
        return sensorValue_17;
    }

    public void setSensorValue_17(String sensorValue_17) {
        this.sensorValue_17 = sensorValue_17;
    }

    public String getSensorValue_18() {
        return sensorValue_18;
    }

    public void setSensorValue_18(String sensorValue_18) {
        this.sensorValue_18 = sensorValue_18;
    }

    public String getSensorValue_19() {
        return sensorValue_19;
    }

    public void setSensorValue_19(String sensorValue_19) {
        this.sensorValue_19 = sensorValue_19;
    }

    public String getSensorValue_20() {
        return sensorValue_20;
    }

    public void setSensorValue_20(String sensorValue_20) {
        this.sensorValue_20 = sensorValue_20;
    }

    // KEEP METHODS - put your custom methods here
    public static ScaleRecord ScaleRecordForSensor(final String SensorType,final Integer IsSend) {
        ScaleRecord scaleRecord=new ScaleRecord();
        switch (SensorType){
            case "02":            case "06":            case "03":            case "04":            case "11":
            case "12":            case "13":            case "21":            case "32":            case "18":
            case "39":
                scaleRecord.ScaleType=WeightType;
                break;
            case "07":            case "09":            case "22":            case "15":            case "23":
            case "19":            case "20":            case "17":            case "24":            case "25":
            case "33":            case "34":            case "35":            case "36":            case "37":
            case "38":            case "30":            case "31":
                scaleRecord.ScaleType=SportType;
                break;
            case "001":            case "071":            case "091":            case "221":            case "151":
                scaleRecord.ScaleType=StepsScaleType;
                break;
            case "002":            case "231":            case "232":
                scaleRecord.ScaleType=SleepScaleType;
                break;
            case "003":            case "171":            case "004":            case "301":            case "311":
                scaleRecord.ScaleType=HeartScaleType;
                break;
        }
        scaleRecord.IsSend=IsSend;
        return scaleRecord;
    }

    public ScaleRecord(Integer ScaleType, Integer IsSend) {
        this.ScaleType=ScaleType;
        this.IsSend=IsSend;
    }

    public void setValue(String SensorType,String SensorValue){
        switch (ScaleType){
            case WeightType:
                switch (SensorType){
                    case "02":  this.sensorValue_01=SensorValue;  break;
                    case "06":  this.sensorValue_02=SensorValue;  break;
                    case "03":  this.sensorValue_03=SensorValue;  break;
                    case "04":  this.sensorValue_04=SensorValue;  break;
                    case "11":  this.sensorValue_05=SensorValue;  break;
                    case "12":  this.sensorValue_06=SensorValue;  break;
                    case "13":  this.sensorValue_07=SensorValue;  break;
                    case "21":  this.sensorValue_08=SensorValue;  break;
                    case "32":  this.sensorValue_09=SensorValue;  break;
                    case "18":  this.sensorValue_10=SensorValue;  break;
                    case "39":  this.sensorValue_11=SensorValue;  break;
                }
                break;
            case SportType:{
                switch (SensorType){
                    case "07": this.sensorValue_01=SensorValue;  break;
                    case "09": this.sensorValue_02=SensorValue;  break;
                    case "22": this.sensorValue_03=SensorValue;  break;
                    case "15": this.sensorValue_04=SensorValue;  break;
                    case "23": this.sensorValue_05=SensorValue;  break;
                    case "19": this.sensorValue_06=SensorValue;  break;
                    case "20": this.sensorValue_07=SensorValue;  break;
                    case "17": this.sensorValue_08=SensorValue;  break;
                    case "24": this.sensorValue_09=SensorValue;  break;
                    case "25": this.sensorValue_10=SensorValue;  break;
                    case "33": this.sensorValue_11=SensorValue;  break;
                    case "34": this.sensorValue_12=SensorValue;  break;
                    case "35": this.sensorValue_13=SensorValue;  break;
                    case "36": this.sensorValue_14=SensorValue;  break;
                    case "37": this.sensorValue_15=SensorValue;  break;
                    case "38": this.sensorValue_16=SensorValue;  break;
                    case "30": this.sensorValue_17=SensorValue;  break;
                    case "31": this.sensorValue_18=SensorValue;  break;
                }
            }
            break;
            case StepsScaleType:{
                switch (SensorType) {
                    case "001": this.sensorValue_01=SensorValue;  break;
                    case "071": this.sensorValue_02=SensorValue;  break;
                    case "091": this.sensorValue_03=SensorValue;  break;
                    case "221": this.sensorValue_04=SensorValue;  break;
                    case "151": this.sensorValue_05=SensorValue;  break;
                }
            }
            break;
            case SleepScaleType:{
                switch (SensorType) {
                    case "002": this.sensorValue_01=SensorValue;  break;
                    case "231": this.sensorValue_02=SensorValue;  break;
                    case "232": this.sensorValue_03=SensorValue;  break;
                }
            }
            break;
            case HeartScaleType:{
                switch (SensorType) {
                    case "003": this.sensorValue_01=SensorValue;  break;
                    case "171": this.sensorValue_02=SensorValue;  break;
                    case "004": this.sensorValue_03=SensorValue;  break;
                    case "301": this.sensorValue_04=SensorValue;  break;
                    case "311": this.sensorValue_05=SensorValue;  break;
                }
            }
            case WeightWifiType:
                switch (SensorType){
                    case "02":  this.sensorValue_01=SensorValue;  break;
                    case "06":  this.sensorValue_02=SensorValue;  break;
                    case "03":  this.sensorValue_03=SensorValue;  break;
                    case "04":  this.sensorValue_04=SensorValue;  break;
                    case "11":  this.sensorValue_05=SensorValue;  break;
                    case "12":  this.sensorValue_06=SensorValue;  break;
                    case "13":  this.sensorValue_07=SensorValue;  break;
                    case "21":  this.sensorValue_08=SensorValue;  break;
                    case "32":  this.sensorValue_09=SensorValue;  break;
                    case "18":  this.sensorValue_10=SensorValue;  break;
                    case "39":  this.sensorValue_11=SensorValue;  break;
                }
                break;
        }
    }
    public String getValue(String SensorType) {
        switch (ScaleType) {
            case WeightType:
                switch (SensorType) {
                    case "02":                        return getSensorValue_01();
                    case "06":                        return getSensorValue_02();
                    case "03":                        return getSensorValue_03();
                    case "04":                        return getSensorValue_04();
                    case "11":                        return getSensorValue_05();
                    case "12":                        return getSensorValue_06();
                    case "13":                        return getSensorValue_07();
                    case "21":                        return getSensorValue_08();
                    case "32":                        return getSensorValue_09();
                    case "18":                        return getSensorValue_10();
                    case "39":                        return getSensorValue_11();
                    default:                        return null;
                }
            case SportType: {
                switch (SensorType) {
                    case "07":                        return getSensorValue_01();
                    case "09":                        return getSensorValue_02();
                    case "22":                        return getSensorValue_03();
                    case "15":                        return getSensorValue_04();
                    case "23":                        return getSensorValue_05();
                    case "19":                        return getSensorValue_06();
                    case "20":                        return getSensorValue_07();
                    case "17":                        return getSensorValue_08();
                    case "24":                        return getSensorValue_09();
                    case "25":                        return getSensorValue_10();
                    case "33":                        return getSensorValue_11();
                    case "34":                        return getSensorValue_12();
                    case "35":                        return getSensorValue_13();
                    case "36":                        return getSensorValue_14();
                    case "37":                        return getSensorValue_15();
                    case "38":                        return getSensorValue_16();
                    case "30":                        return getSensorValue_17();
                    case "31":                        return getSensorValue_18();
                    default:                        return null;
                }
            }
            case StepsScaleType: {
                switch (SensorType) {
                    case "001":                        return getSensorValue_01();
                    case "071":                        return getSensorValue_02();
                    case "091":                        return getSensorValue_03();
                    case "221":                        return getSensorValue_04();
                    case "151":                        return getSensorValue_05();
                    default:                        return null;
                }
            }
            case SleepScaleType:
                switch (SensorType){
                    case "002":                        return getSensorValue_01();
                    case "231":                        return getSensorValue_02();
                    case "232":                        return getSensorValue_03();
                    default:                        return null;
                }
            case HeartScaleType: {
                switch (SensorType) {
                    case "003":                        return getSensorValue_01();
                    case "171":                        return getSensorValue_02();
                    case "004":                        return getSensorValue_03();
                    case "301":                        return getSensorValue_04();
                    case "311":                        return getSensorValue_05();
                    default:                        return null;
                }
            }
            case WeightWifiType:
                switch (SensorType) {
                    case "02":                        return getSensorValue_01();
                    case "06":                        return getSensorValue_02();
                    case "03":                        return getSensorValue_03();
                    case "04":                        return getSensorValue_04();
                    case "11":                        return getSensorValue_05();
                    case "12":                        return getSensorValue_06();
                    case "13":                        return getSensorValue_07();
                    case "21":                        return getSensorValue_08();
                    case "32":                        return getSensorValue_09();
                    case "18":                        return getSensorValue_10();
                    case "39":                        return getSensorValue_11();
                    default:                        return null;
                }
            default:                        return null;
        }
    }

//    public String getModelID(){
//        if(DeviceId==null)
//            return "0000";
//        else
//            return DeviceId.substring(6,10);
//    }

    //    public Object getSensorDataType(String sensorType) {
//        switch (RecordType) {
//            case WeightType:
//                switch (sensorType) {
//                    case "02":
//                        getSensorDataType_01();
//                        break;
//                    case "06":
//                        getSensorDataType_02();
//                        break;
//                    case "03":
//                        getSensorDataType_03();
//                        break;
//                    case "04":
//                        getSensorDataType_04();
//                        break;
//                    case "11":
//                        getSensorDataType_05();
//                        break;
//                    case "12":
//                        getSensorDataType_06();
//                        break;
//                    case "13":
//                        getSensorDataType_07();
//                        break;
//                    case "21":
//                        getSensorDataType_08();
//                        break;
//                    default:
//                        return null;
//                }
//                break;
//            case SportType: {
//                switch (sensorType) {
//                    case "07":
//                        getSensorDataType_01();
//                        break;
//                    case "09":
//                        getSensorDataType_02();
//                        break;
//                    case "22":
//                        getSensorDataType_03();
//                        break;
//                    case "15":
//                        getSensorDataType_04();
//                        break;
//                    case "23":
//                        getSensorDataType_05();
//                        break;
//                    case "19":
//                        getSensorDataType_06();
//                        break;
//                    case "20":
//                        getSensorDataType_07();
//                        break;
//                    case "17":
//                        getSensorDataType_08();
//                        break;
//                    default:
//                        return null;
//                }
//            }
//            default:
//                return null;
//        }
//        return null;
//    }
    @Override
    public String toString() {
        return "ScaleRecord{" +
                "UserId='" + UserId + '\'' +
                ", DeviceId=" + DeviceId +
                ", Timestamp=" + Timestamp +
                ", ScaleType=" + ScaleType +
                ", sensorValue_01=" + sensorValue_01 +
                ", sensorValue_02=" + sensorValue_02 +
                ", sensorValue_03=" + sensorValue_03 +
                ", sensorValue_04=" + sensorValue_04 +
                ", sensorValue_05=" + sensorValue_05 +
                ", sensorValue_06=" + sensorValue_06 +
                ", sensorValue_07=" + sensorValue_07 +
                ", sensorValue_08=" + sensorValue_08 +
                ", sensorValue_09=" + sensorValue_09 +
                ", sensorValue_10=" + sensorValue_10 +
                ", sensorValue_11=" + sensorValue_11 +
                ", sensorValue_12=" + sensorValue_12 +
                ", sensorValue_13=" + sensorValue_13 +
                ", sensorValue_14=" + sensorValue_14 +
                ", sensorValue_15=" + sensorValue_15 +
                ", sensorValue_16=" + sensorValue_16 +
                ", sensorValue_17=" + sensorValue_17 +
                ", sensorValue_18=" + sensorValue_18 +
                ", sensorValue_19=" + sensorValue_19 +
                ", sensorValue_20=" + sensorValue_20 +
                '}';
    }

    public static Comparator Comparator = new Comparator<ScaleRecord>() {
        public int compare(ScaleRecord s1, ScaleRecord s2) {
            if(s1.getTimestamp().compareTo(s2.getTimestamp())==-1){
                return 1;
            }else if (s1.getTimestamp().compareTo(s2.getTimestamp())==1){
                return -1;
            }else{
                return 0;
            }
        }
    };
    // KEEP METHODS END






}
